### PR TITLE
Bugfix metadata

### PR DESCRIPTION
**Pull request by andrea-escartin**
Changes:

- Channel count starts with 1 instead of 0
- Only generate Meta file when converting/recording to csv
- Remove timestamp column

### CODE REVIEW

**Comment by bmeatayi** [comment]
Can we add data and time of the recording to the metadata file?

**Comment by andrea-escartin** [comment]
> Can we add data and time of the recording to the metadata file?

Done!

**Comment by Nujanauss** [comment]
Just FYI I deliberately made the meta file write even if EDF was called because I thought the idea was that the user gets the meta data whatever. @bmeatayi please confirm you'd like meta data to be absent if the user chooses EDF

**Comment by bmeatayi** [comment]
@Nujanauss EDF files have their metadata inside the file, so no need to create an extra file for it.

@andrea-escartin Two suggestions:

- It would be better to change `timestamp` to `DateTime` to avoid confusion with the `timestamp` of the ExG/ORN data.
- I saw that the `timestamp` column is removed from the metadata file in case of binary file conversion. Maybe it is better to keep the column always in the file because of analysis pipelines. It would be easier and consistent for the pipeline if the structure of the file is always the same.

**Comment by andrea-escartin** [comment]
> 

@bmeatayi I have implemented your suggestions: column is renamed to DateTime and it will be created also when converting from .BIN files

**Review by Nujanauss — APPROVED** [review]
Looks good to me

**Pull request merged**
